# Generated by Django 2.0.3 on 2018-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20180502_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
