# Generated by Django 2.0.3 on 2018-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20180511_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Is draft?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Is public?'),
        ),
    ]
