# Generated by Django 2.0.3 on 2018-05-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20180511_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
