# Generated by Django 2.0.3 on 2018-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entry_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='update',
            field=models.BooleanField(default=False, verbose_name='Is Update?'),
        ),
    ]
