# Generated by Django 2.0.3 on 2018-06-15 20:35

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_entry_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='America/Chicago'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Is draft'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='update',
            field=models.BooleanField(default=False, verbose_name='Is Update'),
        ),
    ]
