# Generated by Django 2.1.1 on 2018-10-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, help_text="Introduce yourself with a short description if you'd like.", max_length=800, null=True, verbose_name='Introduction'),
        ),
    ]
